# Generated by Django 4.1.7 on 2023-03-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturers",
                to="app_comments.country",
            ),
        ),
    ]
